#include "drawlookup.h"
#include "settings.h"

const unsigned char drawLookup[] =
{
	FORE_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR
};
