#include "inversedAttribute.h"
#include "settings.h"

const unsigned char inversedAttribute[] =
{
	FORE_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR
};
