#include "normalAttribute.h"
#include "settings.h"

const unsigned char normalAttribute[] =
{
	BACK_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR
};
