#include <Display/standardAttribute.h>
#include "settings.h"

const unsigned char normalAttribute[] =
{
	// Normal
	BACK_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,

	// Inversed
	FORE_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	FORE_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, FORE_COLOR, BACK_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, FORE_COLOR, BACK_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, FORE_COLOR,
	BACK_COLOR, BACK_COLOR, BACK_COLOR, BACK_COLOR
};
